### ISSUE TITLE
show action type/name in diff

### ISSUE THREAD

**Issue by sheltonial** [fcomb/redux-diff-logger#5]
This module is fantastic, though it would be really handy to display the action type/name to give the state diff some context as to what action the user performed.

Eg. say I was firing this action:

```
{
   type: 'FOO',
}
```

The log could show something like `FOO diff @ [time]`

Looking at your source code it should be pretty easy to implement :)

**Comment by imevro** [comment]
I'll merge `redux-diff-logger` to `redux-logger` on this month, because it already have a wide list of features, so diff will be one of them. And yes, it has type in title!

Stay tuned and watch [redux-logger](https://github.com/fcomb/redux-logger) :)
